/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import * as THREE from 'three';
import * as material from './materials';

export function GachaponMachine(props) {
  const { nodes, materials } = useGLTF('./assets/gachapon_machine.gltf')

  return (
    <group {...props} dispose={null}>
      <group position={[-130.6, 333.34, 383.79]}>
        {/* <mesh geometry={nodes.ball_7.geometry} material={material.bubble3} position={[14.33, -20.7, -5.06]} rotation={[3.12, 0.86, 2.72]} scale={[2.62, 2.79, 2.79]} /> */}
        {/* <mesh geometry={nodes.ball_3.geometry} material={material.bubble} position={[-3.3, 1.87, 1.71]} rotation={[3.12, 0.86, 2.72]} scale={2.79} /> */}
      </group>
      {/* <mesh geometry={nodes.ball_4.geometry} material={material.bubble2} position={[75.24, 407.75, 390.93]} rotation={[-0.02, 0, 0]} scale={2.79} /> */}
      {/* <mesh geometry={nodes.ball_5.geometry} material={material.bubble3} position={[-28.54, 267.84, 287.32]} rotation={[-0.02, 0, -0.09]} scale={2.79} /> */}

      <group position={[-69.6, 214.73, 254.42]}>
        <group position={[-215.5, 425.27, -289.3]} rotation={[1.55, 0, 0]} scale={[1.55, 2.06, 1.55]}>
          <pointLight intensity={0.84} decay={2} distance={2001} position={[-1.3, 0, -0.06]} />
          {/* <mesh geometry={nodes.Sphere_2_3.geometry} material={material.bluelight} position={[-0.82, 1.05, 2.18]} rotation={[-Math.PI / 2, 0, 0]} /> */}
        </group>
        {/* <group position={[-315.99, 84.31, -151.07]} rotation={[1.55, 0, 0]} scale={[1.55, 2.06, 1.55]}>
          <pointLight intensity={0.45} decay={2} distance={321} position={[-1.3, 0, -0.06]} />
          <mesh geometry={nodes.Sphere_2_4.geometry} material={material.bluelight} position={[-0.82, 1.05, 2.18]} rotation={[-Math.PI / 2, 0, 0]} />
        </group> */}
        {/* <group position={[-563.4, 197.83, -153.84]} rotation={[1.55, 0, 0]} scale={[1.55, 2.06, 1.55]}>
          <pointLight intensity={0.45} decay={2} distance={321} position={[-1.3, 0, -0.06]} />
          <mesh geometry={nodes.Sphere_2_5.geometry} material={material.bluelight} position={[-0.82, 1.05, 2.18]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group position={[565.4, 264.91, -69.27]} rotation={[1.55, 0, 0]} scale={[1.55, 2.06, 1.55]}>
          <pointLight intensity={0.45} decay={2} distance={321} position={[-1.3, 0, -0.06]} />
          <mesh geometry={nodes.Sphere_2_6.geometry} material={material.bluelight} position={[-0.82, 1.05, 2.18]} rotation={[-Math.PI / 2, 0, 0]} />
        </group> */}
        {/* <group position={[-448.23, -172.13, 205.25]} rotation={[1.55, 0, 0]} scale={[1.55, 2.06, 1.55]}>
          <pointLight intensity={0.45} decay={2} distance={321} position={[-1.3, 0, -0.06]} />
          <mesh geometry={nodes.Sphere_2_7.geometry} material={material.bluelight} position={[-0.82, 1.05, 2.18]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group position={[538.64, -424.72, 289.28]} rotation={[1.55, 0, 0]} scale={[1.55, 2.06, 1.55]}>
          <pointLight intensity={2.04} decay={2} distance={1400} position={[-1.3, 0, -0.06]} />
          <mesh geometry={nodes.Sphere_2_8.geometry} material={material.bluelight} position={[-0.82, 1.05, 2.18]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group position={[439.69, 38.76, 200.51]} rotation={[1.55, 0, 0]} scale={[1.55, 2.06, 1.55]}>
          <pointLight intensity={0.45} decay={2} distance={321} position={[-1.3, 0, -0.06]} />
          <mesh geometry={nodes.Sphere_2_9.geometry} material={material.bluelight} position={[-0.82, 1.05, 2.18]} rotation={[-Math.PI / 2, 0, 0]} />
        </group> */}
      </group>

      <group position={[-143.47, 432.63, 304.15]} rotation={[1.55, 0, 0]} scale={[1.55, 2.06, 1.55]}>
        <pointLight intensity={0.2} decay={2} distance={321} position={[-1.3, 0, -0.06]} />
        {/* <mesh geometry={nodes.Sphere_2.geometry} material={material.bluelight} position={[-0.82, 1.05, 2.18]} rotation={[-Math.PI / 2, 0, 0]} /> */}
      </group>
      <group position={[109.32, 338.25, 443.33]} rotation={[1.55, 0, 0]} scale={[1.55, 2.06, 1.55]}>
        <pointLight intensity={0.2} decay={2} distance={321} position={[-1.3, 0, -0.06]} />
        {/* <mesh geometry={nodes.Sphere_2_1.geometry} material={material.bluelight} position={[-0.82, 1.05, 2.18]} rotation={[-Math.PI / 2, 0, 0]} /> */}
      </group>
      <group position={[-38.04, 245.04, 455.14]} rotation={[1.55, 0, 0]} scale={[1.55, 2.06, 1.55]}>
        <pointLight intensity={0.2} decay={2} distance={321} position={[-1.3, 0, -0.06]} />
        {/* <mesh geometry={nodes.Sphere_2_2.geometry} material={material.bluelight} position={[-0.82, 1.05, 2.18]} rotation={[-Math.PI / 2, 0, 0]} /> */}
      </group>

      {/* <directionalLight intensity={0.09} decay={2} position={[-940.34, -185.75, -34.09]} rotation={[1.75, -1.37, -2.96]} />
      <directionalLight intensity={0.12} decay={2} position={[-36.71, 306.26, 1499.73]} rotation={[-0.2, -0.02, 0.12]} />
      <directionalLight intensity={0.09} decay={2} position={[-782.07, 1136.08, 1499.73]} rotation={[-0.65, -0.39, 0.47]} />
      <directionalLight intensity={0.46} decay={2} position={[457.6, 300, -639.83]} rotation={[-2.7, 0.57, 0.86]} />
       */}
      {/* <PerspectiveCamera makeDefault={false} far={100000} near={5} fov={45} position={[-43.88, 218.96, 1766.62]} /> */}
      {/* <mesh geometry={nodes.ball_6.geometry} material={nodes.ball_6.material} position={[66.71, 382.12, 396.39]} rotation={[-0.02, 0, 0]} scale={2.79} /> */}


      {/* <mesh geometry={nodes.Icosahedron_3.geometry} material={material.gem} position={[65.06, 257.45, 427.28]} rotation={[-1.38, 1.01, -0.06]} scale={[2.06, 2.79, 0.36]} /> */}
      {/* <mesh geometry={nodes.Icosahedron_3_1.geometry} material={material.gem} position={[-94.83, 243.73, 386.02]} rotation={[0.15, 0.33, -0.61]} scale={[2.06, 2.79, 2.79]} /> */}
      {/* <mesh geometry={nodes.Icosahedron_2.geometry} material={material.gem} position={[-80.67, 377.02, 452.74]} rotation={[-0.99, -0.3, -0.51]} scale={[2.06, 2.79, 0.36]} /> */}
      {/* <mesh geometry={nodes.Backdrop.geometry} material={nodes.Backdrop.material} position={[422.65, -252.88, -2179.52]} rotation={[0.08, 0, 0]} scale={[1, 1, 2.53]} /> */}
      {/* <mesh geometry={nodes.Icosahedron.geometry} material={material.gem} position={[44.39, 474.58, 403.2]} rotation={[-0.13, 0.47, 0.46]} scale={[2.06, 2.79, 2.79]} /> */}

      <mesh geometry={nodes.Cylinder.geometry} material={material.paleyellow} position={[-16.14, -92.99, 364.3]} rotation={[3.14, 0, 0]} scale={2.79} />
      <mesh geometry={nodes.Torus_3.geometry} material={material.pink} position={[-23.98, -10.81, 519]} rotation={[-0.02, 0, 0]} scale={2.79} />
      {/* <mesh geometry={nodes.Star.geometry} material={material.yellow} position={[-27.83, 109.66, 518.23]} rotation={[0, 0, 0]} scale={2.79} /> */}
      <mesh geometry={nodes.Torus.geometry} material={material.pink} position={[-18.99, 185.9, 384.13]} rotation={[-1.6, 0, 0]} scale={[2.79, 2.76, 2.79]} />
      <mesh geometry={nodes.Torus_2.geometry} material={material.pink} position={[-19.68, -100.74, 382.08]} rotation={[-1.6, 0, 0]} scale={2.79} />
      <mesh geometry={nodes.Sphere.geometry} material={material.glass} position={[-16.8, 357.19, 378.75]} scale={2.79} />
      <mesh geometry={nodes.Boolean.geometry} material={material.paleyellow} position={[-21.56, -13.82, 520.61]} rotation={[1.55, 0, 0.11]} scale={2.79}>
        {/* <mesh geometry={nodes.hole.geometry} material={material.glass} rotation={[-Math.PI / 2, 0, 0]} /> */}
        <mesh geometry={nodes.Cylinder_1.geometry} material={material.paleyellow} position={[-4.81, -47.94, -19.94]} rotation={[-1.57, 0, 0]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/assets/gachapon_machine.gltf')
