import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {GachaponMachineCanvas} from '../components/GachaponMachineCanvas';
import { Dialogue } from '../components/dialogue';
import { getWelcomeText } from '../components/dialoguetext';
import { useEffect, useState } from 'react';

const Home: NextPage = () => {
  const [welcomeText, setWelcomeText] = useState('');

  useEffect( () => {
    setWelcomeText(getWelcomeText());
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <GachaponMachineCanvas/>
        <Dialogue text={welcomeText}/>
      </main>
    </div>
  )
}

export default Home
